name: Daily Usage Report

on:
  schedule:
    - cron: '0 13 * * *'

jobs:
  send-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send daily email report
        env:
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          MAILGUN_FROM: ${{ secrets.MAILGUN_FROM }}
          MAILGUN_TO: ${{ secrets.MAILGUN_TO }}
        run: |
          python app/tasks/email_report.py
